/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // not compatible with Java21
    // id("io.freefair.lombok") version "8.3"

    id("org.gradlex.extra-java-module-info") version "1.4.2"
    id("org.beryx.jlink") version "3.0.0"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    mavenCentral()
}

extraJavaModuleInfo {
    failOnMissingModuleInfo.set(false)
    module("org.jodd:jodd-mail", "jodd.mail") {
        requiresTransitive("jakarta.mail")
        exports("jodd.mail")
        //exports("jakarta.mail")
    }
    automaticModule("com.joestelmach:natty", "com.joestelmach.natty")
}

dependencies {
    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")

    testCompileOnly("org.projectlombok:lombok:1.18.30")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.30")


    implementation("com.google.code.gson:gson:2.10.1")

    implementation("jakarta.mail:jakarta.mail-api:2.1.2")
    implementation("org.eclipse.angus:jakarta.mail:2.0.2")
    implementation("org.jodd:jodd-mail:7.0.1")

    implementation("com.joestelmach:natty:0.13")


    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    // Define the main class for the application
    mainClass.set("cz.vakabus.reminderbot.App")
    mainModule.set("reminderbot")
}

jlink {
    options.addAll("--strip-debug", "--compress", "2", "--no-header-files", "--no-man-pages")
    launcher{
        name = "reminderbot"
        // jvmArgs = []
    }
    forceMerge("jakarta.mail")
}